services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    depends_on:
      - mongo
    env_file: .env
    ports: 
      - '3000:3000'
    # volumes:
    #   - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    depends_on:
      - mongo
    env_file: .env
    ports: 
      - '3001:3000'
    # volumes:
    #   - .:/usr/src/app

  mongo:
    image: mongo:latest
