services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    depends_on:
      - mongo
    env_file: ./apps/reservations/.env 
    ports: 
      - '3000:3000'
    # volumes:
    #   - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    depends_on:
      - mongo
    env_file: ./apps/auth/.env
    ports: 
      - '3001:3000'
    develop:
      watch:
        - action: sync
          path: ./apps/auth
          target: /usr/src/app/apps/auth
          ignore:
            - node_modules/
    # volumes:
    #   - .:/usr/src/app

  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 

